export const MAIN_REF = "MAIN_REF";
export const REQUEST_FAILED = "REQUEST_FAILED";
//
export const SEARCH_SCROLL_REQUEST = "SEARCH_SCROLL_REQUEST";
export const SCROLL_SUCCES = "SCROLL_SUCCES";
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCES = "SEARCH_SUCCES";
export const SEARCH_FAILED = "SEARCH_FAILD";
//
export const SET_USER = "SET_USER";

//
export const SUBTITLES_REQUEST = "SUBTITLES_REQUEST";
export const SUBTITLES_SUCCES = "SUBTITLES_SUCCES";
export const FOCUS_CAPTIONS = "FOCUS_CAPTIONS";
export const TEXT_TRANSLATE_REQUEST = "TEXT_TRANSLATE_REQUEST";
export const TEXT_TRANSLATE_SUCCES = "TEXT_TRANSLATE_SUCCES";

export const LANGUAGES_REQUEST = "LANGUAGE_REQUEST";
export const LANGUAGES_SUCCES = "LANGUAGE_SUCCES";
export const SET_LANGUAGE = "SET_LANGUAGE";
